version: 0.2
phases:
  install: 
    runtime-versions:
      docker: 18
    commands: 
      - apt-get update -y
      - apt-get install -y jq
  build:
    commands:
      - echo "teste" >> elb.txt
      - ls
      - echo $stackName
      - aws cloudformation --region us-east-1 describe-stacks --stack-name $stackName
      - bucket=$(aws cloudformation --region us-east-1 describe-stacks --stack-name $stackName --query "Stacks[0].Outputs[?OutputKey=='S3Name'].OutputValue" --output text)
      - aws s3 cp 404.html s3://$bucket/404.html
      - aws s3 cp index.html s3://$bucket/index.html
      - aws s3 cp style.css s3://$bucket/style.css
  post_build:
    commands:
      - echo "DONE!!!!"
    
artifacts:
  files: 
    - elb.txt